### ISSUE TITLE
reduce build system complexity 

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#101]
_From [rdeltour@gmail.com](https://code.google.com/u/rdeltour@gmail.com/) on September 09, 2011 15:26:21_

There are many meta files required for a project/module:

```
 * expath-pkg.xml
 * pom.xml
 * build.properties
 * META-INF/MANIFEST.MF
 * OSGI-INF/service.xml
```

Also, setting up Eclipse can sometimes be a chore.

Can the build system be simplified ?

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=101_

**Comment by btiernay** [comment]
Hi all. Very interested in your work here. I read a slide deck that mentioned "1 - 3 have been merged" which I believe concerned OSGi manifests, SCR components and XML catalogs. Curious how this was done and where I can look for an example. Cheers!
