### ISSUE TITLE
the data directory of a volatile job is not always deleted if things went wrong

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#149]
_From [rdeltour@gmail.com](https://code.google.com/u/rdeltour@gmail.com/) on February 20, 2012 16:05:30_

When the job execution failed or the fwk crashed, the data directory of a job is sometimes left on the file system. It should be systematically cleaned after execution, no matter what happens.

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=149_

**Comment by bertfrees** [comment]
@rdeltour I saw that on 25 Apr 2016 Javi implemented a `org.daisy.pipeline.ws.cleanuponstartup` configuration setting (https://github.com/daisy/pipeline-framework/commit/43b4adbc), I think in response to https://github.com/daisy/pipeline-framework/issues/105. This also fixes the "when the fwk crashed" part of this issue right?

If I understand correctly, when the job failed, it is the responsibility of the client to delete it. So  that means that if there is a bug it must be in one of the clients, right? Do you remember why you created this issue?

**Comment by bertfrees** [comment]
John Brugge says:

>As for whether this is still an issue, I’m not sure. I can see in the console output that a job that finishes with a status of DONE gets cleaned up properly, but I don’t know about cleanup after a restart or crash.
> 
> We haven’t installed v1.10 yet, but I’ll make note of that configuration property.

I'm going to close the issue for now. We'll reopen it when Benetech confirms it is still an issue.
