### ISSUE TITLE
Ability to stop/kill a job before it's finished running

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#168]
_From [josteinaj@gmail.com](https://code.google.com/u/josteinaj@gmail.com/) on April 30, 2012 13:59:44_

Due to script bugs or unexpected input documents a script may spend a lot of time and resources running, so a way of killing it would be useful. Having access to the job log after killing it would also be useful to be able to find out what went wrong.

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=168_

**Comment by bertfrees** [comment]
Duplicate: https://github.com/daisy/pipeline-framework/issues/76

**Comment by bertfrees** [comment]
Replaced by https://github.com/daisy/pipeline-framework/issues/76
