### ISSUE TITLE
Support custom XSD datatypes

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#174]
_From [marisa.d...@gmail.com](https://code.google.com/u/115886856648841171353/) on May 29, 2012 04:17:50_

Implement this: http://code.google.com/p/daisy-pipeline/wiki/ScriptMetadataCleanup?ts=1338249026&updated=ScriptMetadataCleanup#Custom_XSD_Data_Types

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=174_

**Comment by bertfrees** [comment]
see https://github.com/daisy/pipeline-framework/pull/84
