### ISSUE TITLE
The default values for options and ports are not exposed through the Web API

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#188]
_From [josteinaj@gmail.com](https://code.google.com/u/josteinaj@gmail.com/) on July 10, 2012 18:01:50_

What steps will reproduce the problem? 1. Start Pipeline 2 in local mode
2. GET http://localhost:8181/ws/scripts/daisy202-to-epub3
3. Inspect the "mediaoverlay" and "compatibility-mode" options What is the expected output? What do you see instead? The "mediaoverlay" and "compatibility-mode" options returned are:

``` xml
<option desc="Whether or not to include media overlays and associated audio files (true or false)." mediaType="" name="mediaoverlay" ordered="true" required="false" sequence="false" type="boolean"/>
<option desc="Whether or not to include NCX-file, OPF guide element and ASCII filenames (true or false)." mediaType="" name="compatibility-mode" ordered="true" required="false" sequence="false" type="boolean"/>
```

They correctly have the `@required="false"` attribute set, indicating that the WS knows that a default value is present. However, the default values are not exposed.

It was agreed upon when talking about the [ http://code.google.com/p/daisy-pipeline/wiki/F2F201204_Oslo#Script_Metadata_Cleanup Script Metadata Cleanup] that the default values should be exposed, but I don't think we described concretely how. Maybe simply `@default="defaultvalue"`?

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=188_

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-framework/pull/90
