### ISSUE TITLE
Easier framework installation; bundle Java?

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#296]
_From [josteinaj@gmail.com](https://code.google.com/u/josteinaj@gmail.com/) on April 23, 2013 13:05:26_

Would it be an option to bundle Java with Pipeline 2? That way we would avoid misconfigured or wrong versions of Java being used.

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=296_

**Comment by bertfrees** [comment]
We have been bundling the JRE for some time now.
