### ISSUE TITLE
Dynamic enumeration of custom datatypes

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#330]
_From [josteinaj@gmail.com](https://code.google.com/u/josteinaj@gmail.com/) on June 20, 2013 15:59:45_

We want to allow the end-user to use (for instance) their own braille translation tables or their own TTS engine, not declared/bundled with the default Pipeline 2 distribution.

For the Braille scripts, this is currently done using the "translator" option, where you can specify a URL to a translator.

Dynamic enumeration of custom datatypes would allow the user to install custom braille tables and custom TTS engines, and they would appear in a dropdown-list or multiple-choice list in the UIs.

[1] http://code.google.com/p/daisy-pipeline/wiki/ScriptMetadataCleanup#Custom_XSD_Data_Types

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=330_

**Comment by bertfrees** [comment]
see https://github.com/daisy/pipeline-framework/pull/84

**Comment by bertfrees** [comment]
Datatypes have been implemented in the framework (see https://github.com/daisy/pipeline-framework/pull/84) and we have come up with a standard syntax to define enumerations and patterns. Static datatypes are created with org.daisy.pipeline.datatypes.UrlBasedDatatypeService. modules-build-helper automatically creates an UrlBasedDatatypeService if it finds a `px:data-type` attribute in catalog.xml, or if it finds a `px:data-type` element inside the `p:pipeinfo` of a `p:option`.

Dynamic datatypes can be created with your own implementation of org.daisy.pipeline.datatypes.DatatypeService.
