### ISSUE TITLE
split large text files by size

### ISSUE THREAD

**Issue by ghost** [daisy/pipeline#351]
_From [rdeltour@gmail.com](https://code.google.com/u/rdeltour@gmail.com/) on July 17, 2013 11:44:27_

Some producers will have existing content with only one really huge (3MB+) text content document (XHTML or DTBook format). We should have an option in our conversion scripts to split this into several smaller files in the EPUB output. Having several smaller text files improves performance dramatically in reading systems.

The html-utils module contains an XSLT that split an XHTML document based in its structure,  but it would be nice to also have an option to split the text content document based on KB.

See also issue https://github.com/daisy/pipeline/issues/309

_Original issue: http://code.google.com/p/daisy-pipeline/issues/detail?id=351_

**Comment by bertfrees** [comment]
Should be prioritized at some point, since it causes issues on some reading systems with large books.

**Comment by josteinaj** [comment]
There's a [splitter in the nordic migrator](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/xproc/step/html-split.xpl). It doesn't split by KB though and expects certain things from the input.

We'll probably need a better splitter later this year at NLB as we plan to use a single-HTML unzipped EPUB as our master format and then split into multiple files for distribution.

**Comment by bertfrees** [comment]
OK thanks for the info!

**Comment by bertfrees** [comment]
This was fixed by https://github.com/daisy/pipeline-scripts/pull/149
