### ISSUE TITLE
Space normalization with zedai-to-html

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline#423]
Space normalization can be a bit aggressive sometimes. For example on this modification of one of alice.xml's verses:

Zedai input:
`
<ln><emph>All</emph> <emph>in</emph> <emph>the</emph> <emph>golden</emph> <emph>afternoon</emph></ln>
`

HTML ouput:

```
<span><em>All</em><em>in</em><em>the</em><em>golden</em><em>afternoon</em></span>
```

This can be quite a problem with `w` elements, especially if not inside any noticeable `s` element.

What do we need normalization for? Readability, cleanliness, output size?

As an alternative, could we only merge sequences of white spaces into single spaces?

**Comment by bertfrees** [comment]
Has been fixed in https://github.com/daisy/pipeline-scripts/commit/8f4da41e9b08d9c65a7c09855784d1c81ed7b296 (https://github.com/daisy/pipeline-assembly/issues/94).
