### ISSUE TITLE
Ability to declare fileset types in scripts and provide them through the (Web) API

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#426]
As the number of scripts grow, it could be convenient to be able to filter the list of scripts based on the kind of fileset you want to put in or the kind fileset you want to get out. For instance:
- User uploads a EPUB3 file; UI can then hide scripts which does not allow EPUB3 as input
- User clicks a "I want to produce EPUB3" button; UI can then hide scripts which does not give EPUB3 as output

I don't think we can quite achieve this currently with the way we declare the media type on inputs and options. For instance, there's no distinction between a DAISY 2.02 fileset and a pure-HTML fileset. Or a EPUB3 and a EPUB2 fileset.

(this is more of a "nice to have" feature; it's not critical but would be useful)

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-framework/pull/84
