### ISSUE TITLE
Batch conversions

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#431]
So I've had a [littlebit of experience](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/tree/master/batch-converter) with batch conversions with Pipeline 2 here at NLB now. I'm converting a directory of 4000+ DTBooks to EPUB3. It takes a lot of time (a couple of days probably if I tried to convert everything, I'm currently converting 100 random books at a time).

The features needed to support batch conversions using Pipeline 2 as I see it is:
- the ability to associate a "batch ID" with a job
- the ability to get the status for a batch ID; i.e. number of jobs in each of the possible job states
- the ability to list all jobs associated with a batch ID
- the ability to delete all jobs associated with a batch ID
- the ability to get a HTML report for a batch ID, with links to individual jobs (execution log, detailed log, reports, outputs, option values, ...)

wdyt?

**Comment by capitancambio** [comment]
https://github.com/daisy/pipeline-framework/pull/79
