### ISSUE TITLE
Move html-utils to the pipeline-modules-common repository

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#453]
`px:fileset-load` depends on html-utils for loading HTML files. If we move html-utils to the pipeline-modules-common repository, we can decouple the pipeline-modules-common repository from the pipeline-scripts-utils repository. I think we should avoid having modules in modules-common that depend on modules outside of modules-common.

**Comment by bertfrees** [comment]
This has been done in https://github.com/daisy/pipeline-modules-common/commit/a1c8a4a2bd1d8e3eb4258ac42925e9e0891fff6c. It would have been simpler to have all scripts-utils and modules-common in the same repo.
