### ISSUE TITLE
Either move metadata-utils, or the format-specific parts of it, to scripts-utils

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#454]
metadata-utils depends on schemas in the dtbook-validator script. I think we should avoid having modules in modules-common that depend on modules outside of modules-common.

I think we should move the schemas used in dtbook-validator (scripts repo) over to dtbook-utils (scripts-utils repo), and also move the dtbook-specific parts of metadata-utils (modules-common repo) into scripts-utils (or maybe just move the entire metadata-utils module).

**Comment by bertfrees** [comment]
This has been done in https://github.com/daisy/pipeline-scripts-utils/commit/0c28b51fb2f273d8d41a9fbdc964014871ee1dd8 and https://github.com/daisy/pipeline-scripts-utils/commit/451dd40c1577b37bf3ebdc00b63f69c08cd58f31.
