### ISSUE TITLE
Write dtbook-to-epub3's TTS logs in the right directory

### ISSUE THREAD

**Issue by rom1mouret** [daisy/pipeline#456]
Presently, TTS logs for dtbook-to-epub3 are located in `jobs/{job-id}/output/temp-dir/tts-log.xml`. They can be read by admins only if the job is purposely cancelled or if it failed.
It was a convenient solution because `zedai-to-epub3.convert` is only aware of `$temp-dir`, leaving to epub3-store (in dtbook-to-epub3) the responsibility to deal with the final output directory. 
Ideally the logs should be written in the final output directory, outside the EPUB zip package.

**Comment by rdeltour** [comment]
@bertfrees I don't think this was done. Removing the milestone from now, we'll need to re-schedule.

**Comment by bertfrees** [comment]
AFAIK, no. There is also this related issue: https://github.com/daisy/pipeline-tasks/issues/103

**Comment by bertfrees** [comment]
This should be fixed by making tts-log into an output port.

**Comment by bertfrees** [comment]
Fixed by [eb80f7eb59e4fee86cd08625088e18c497c5fc94](https://github.com/daisy/pipeline-modules/commit/eb80f7eb59e4fee86cd08625088e18c497c5fc94)
