### ISSUE TITLE
Add option of force delete running/idle/queued jobs

### ISSUE THREAD

**Issue by capitancambio** [daisy/pipeline#474]
Sometime some jobs will remain with these statuses after a crash or a force shut down. Add a flag to the delete api so we can force the deletion

**Comment by capitancambio** [comment]
see https://github.com/daisy/pipeline-framework/issues/105

**Comment by josteinaj** [comment]
Would this allow stopping of jobs that are *actually* (not *apparently*) running as well? If not, what would happen if one tried?

**Comment by capitancambio** [comment]
That's a really good point. It might create some unexpected behaviours and it might leave some files unaccounted for. This is not a good idea, I'll roll back to the clean at start up time approach.

**Comment by rdeltour** [comment]
Merged.
