### ISSUE TITLE
GUI doesn't show all script options for DTBook to PEF

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline#484]
Seen on OSX only

**Comment by bertfrees** [comment]
I'm gonna close this when it has been merged upstream.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-gui/commit/9db796079d12eff3264e245045dd239eb50b0ff0

**Comment by bertfrees** [comment]
Can be tried on [bugfix-484](https://github.com/daisy/pipeline/tree/bugfix-484) branch
