### ISSUE TITLE
updater should not start with / in the deployPath

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#488]
Unless you specify `-install-dir`, it will try to install to the system root directory when the deployPath starts with `/`.

Also, we should consider setting the default install dir to the parent directory of the updater binary, so that by default the install dir is the `daisy-pipeline` directory.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-updater/pull/2.

**Comment by josteinaj** [comment]
Yes. Closing this as well.
