### ISSUE TITLE
updater should have a better default URL

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#489]
Currently `-service` defaults to `http://defaultservice.com`. It should default to something like `https://daisy.github.io/pipeline/updates`, `http://central.maven.org/maven2/org/daisy/pipeline/updater/1.0.0`, or wherever we end up storing the update descriptor.

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-updater/pull/2. I think it's better to make the option mandatory.

**Comment by josteinaj** [comment]
Ah, didn't see that issue, thanks. I'll close this one then.
