### ISSUE TITLE
Installation instructions reference DEB and RPM, but there's only a ZIP

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#515]
- [Website installation instructions](http://daisy.github.io/pipeline/Get-Help/User-Guide/Installation/)
- [Website download links](https://daisy.github.io/pipeline/Download.html)
- [Github releases](https://github.com/daisy/pipeline-assembly/releases)
- [Maven Central releases](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.daisy.pipeline%22%20AND%20a%3A%22assembly%22) (last DEB on maven central is for 1.9.15)

**Comment by bertfrees** [comment]
OK good point.

**Comment by bertfrees** [comment]
This was fixed in the latest release.
