### ISSUE TITLE
java.xml.bind not available in Java 11

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#534]
### Expected Behavior

Running with Java 11 should work.

### Actual Behavior

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.xml.bind not found
```

### Steps to Reproduce

I'm running the docker image from nlbdev/pipeline, but I expect the same issue will occur with the official Pipeline 2 code.

### Details

According to [this](https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist), java.xml.bind was deprecated as of Java 9, and removed as of Java 11.

### Environment

* Operating system: Linux
* DAISY Pipeline 2 version: 1.11.2-SNAPSHOT
* Interface: docker / command line
* Java version: 11

**Comment by bertfrees** [comment]
Yes, Java 11 is not supported. There are some other issues besides this one too.

On my java-11 branch I did the following:

```diff
eval exec "\"$JAVA"\" "$JAVA_OPTS" \
          --illegal-access=warn \
          --add-opens java.base/java.security=ALL-UNNAMED \
          --add-opens java.base/java.net=ALL-UNNAMED \
          --add-opens java.base/java.lang=ALL-UNNAMED \
          --add-opens java.base/java.util=ALL-UNNAMED \
+         --add-opens java.naming/javax.naming.spi=ALL-UNNAMED \
+         --add-opens java.rmi/sun.rmi.transport.tcp=ALL-UNNAMED \
          --add-exports=java.base/sun.net.www.protocol.http=ALL-UNNAMED \
          --add-exports=java.base/sun.net.www.protocol.https=ALL-UNNAMED \
          --add-exports=java.base/sun.net.www.protocol.jar=ALL-UNNAMED \
-         --add-exports=java.xml.bind/com.sun.xml.internal.bind.v2.runtime=ALL-UNNAMED \
          --add-exports=jdk.xml.dom/org.w3c.dom.html=ALL-UNNAMED \
          --add-exports=jdk.naming.rmi/com.sun.jndi.url.rmi=ALL-UNNAMED \
-         --add-modules java.xml.ws.annotation,java.corba,java.transaction,java.xml.bind,java.xml.ws \
          -Dorg.daisy.pipeline.home="\"$PIPELINE2_HOME"\" \
          -Dorg.daisy.pipeline.data="\"$PIPELINE2_DATA"\" \
          -Dfelix.config.properties="\"file:$PIPELINE2_HOME/etc/config.properties"\" \
          -Dfelix.system.properties="\"file:$PIPELINE2_CONFIG/system.properties"\" \
          $FELIX_OPTS $MODE -classpath "\"$CLASSPATH"\" $MAIN "\"$@\""
```

If I remember correctly it worked fine after this change, except that I have disabled persistence. I think that was the only problem left. I'll probably have to add some module that implements the java.xml.bind.

**Comment by josteinaj** [comment]
I changed to Java 10 for the time being, so I'm fine for now.

**Comment by bertfrees** [comment]
Fixed on develop branch.
