### ISSUE TITLE
Web API documentation: Links to example responses are broken

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#535]
Web API documentation: http://daisy.github.io/pipeline/WebServiceAPI/

this: `https://…/webservice/samples/xml-formats/job.xml`
should be: `https://…/webservice-utils/doc/xml-formats/job.xml`

etc.

**Comment by bertfrees** [comment]
Thanks. Actually I would like to include the samples in the website itself, but the Github links are convenient because of the syntax highlighting.

**Comment by bertfrees** [comment]
Fixed in 7297b96.

Turns out I had already fixed this but not pushed yet.
