### ISSUE TITLE
Acapela adapter not exposed

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline#555]
Pipeline version tested : 1.12.1

The adapter service for acapela TTS engine is not exposed when launching the pipeline.
The wrong package seems to be exposed in the tts-adapter-acapela pom file.

**Comment by bertfrees** [comment]
Right. I remember having fixed this on my "nnels" branch. But it hasn't gotten on master yet.

**Comment by bertfrees** [comment]
@NPavie thanks. Merged in https://github.com/daisy/pipeline-modules/commit/34fc60f108ead7dac1031e5e7f5d81b34a42de2a and tested that it works.
