### ISSUE TITLE
dp2 CLI command not found ubuntu 20.04

### ISSUE THREAD

**Issue by Sanctusz** [daisy/pipeline#563]
### Expected Behavior
Run commands using CLI in Ubuntu 20.04

dp2 help etc.

### Actual Behavior
![image](https://user-images.githubusercontent.com/3602836/89519685-49d1ae00-d7cc-11ea-9f23-b45ba398b1f2.png)

Then I tried running what I assume to be the dp2 file directly inside of /opt/daisy-pipeline2/bin

and I get this
"pipeline2: Program must be run as user `pipeline2'. Try: su pipeline2 -s ./pipeline2 help"

Even if I try to run it as pipeline2 it says "su: using restricted shell /usr/sbin/nologin
This account is currently not available."

### Steps to Reproduce
Provide a list of steps taken to reproduce the problem.
1. Install deb package in Ubuntu 20.04 using dpkg
2. Run dp2

### Details
The CLI is working without issue in my Windows installation but I need it to work on Ubuntu Server.

Is there an environment variable I can set so dp2 command starts working? (why isn't it easy to find in the documentation)

Surely I must be missing something obvious.

### May be a valid path to use CLI

https://github.com/daisy/pipeline-cli-go
Is this required to run dp2 in terminal?

Update: Some of the dependencies go get links are redundant / not working

### Environment
* Operating system: Ubuntu 20.04.1 LTS
* DAISY Pipeline 2 version: 1.13.0
* Interface: CLI / Service

### Log

[daisy-pipeline-webservice.log](https://github.com/daisy/pipeline/files/5034218/daisy-pipeline-webservice.log)

**Comment by bertfrees** [comment]
Hello Jóhann. The command line interface is not included in the daisy-pipeline2 package. It has its own package called daisy-pipeline2-cli. When installed, you will find the executable at /opt/daisy-pipeline2-cli/dp2. You can download the Debian file from https://github.com/daisy/pipeline-cli-go/releases.

**Comment by Sanctusz** [comment]
I will try it out first thing Monday, thank you.
