### ISSUE TITLE
ubuntu 20.4 JAVA_HOME not set/ java command not found/ dp2 not executed

### ISSUE THREAD

**Issue by tigexplorer** [daisy/pipeline#583]
Please fill out the outline following the instructions below. Remember, this is for reporting bugs and issues and not a place to ask questions. For that, you can contact us via our [developers mailing list](https://groups.google.com/forum/#!forum/daisy-pipeline-dev)

### Expected Behavior
The command `dp2` may be executed 

### Actual Behavior
`db2` is unknown

### Steps to Reproduce

1. installing `sudo dpkg -i pipeline2-1.12.1_debian.deb` 
2. installing `sudo dpkg -i cli-2.1.4-linux_386.deb`
3. check `service daisy-pipeline2 status`
```
● daisy-pipeline2.service - LSB: Start and stop the DAISY Pipeline 2 server
     Loaded: loaded (/etc/init.d/daisy-pipeline2; generated)
     Active: active (exited) since Mon 2021-02-15 21:09:54 CET; 41min ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 0 (limit: 4517)
     Memory: 0B
     CGroup: /system.slice/daisy-pipeline2.service

Feb 15 21:09:53 note systemd[1]: Starting LSB: Start and stop the DAISY Pipeline 2 server...
Feb 15 21:09:54 note daisy-pipeline2[5733]: pipeline2: JAVA_HOME not set; results may vary
Feb 15 21:09:54 note daisy-pipeline2[5733]: pipeline2: java command not found
Feb 15 21:09:54 note systemd[1]: Started LSB: Start and stop the DAISY Pipeline 2 server.
```

```
dp2
Der Befehl 'dp2' wurde nicht gefunden, meinten Sie:

  Befehl 'dp' aus dem deb speech-tools (1:2.5.0-8build1)
  Befehl 'd52' aus dem deb d52 (3.4.1-1.1build1)
  Befehl 'dpe' aus dem deb delly (0.8.2-1)
  Befehl 'dpt' aus dem deb pkg-perl-tools (0.59)

Versuche: sudo apt install <deb name>
```

### Details
If necessary, describe your problem in more detail.

None.

### Environment
* Operating system: ubuntu 20.4
* DAISY Pipeline 2 version: 1.12.1
* Interface: _example_: GUI, Command Line, or WebUI
* openjdk version "11.0.10" 2021-01-19
### Logs
Visit [Providing Logs in an Issue](https://daisy.github.io/pipeline/Get-Help/Issue-Tracker.html) for details on how to provide your log files.

[Logs]( link goes here )
The dir `var/log/pipeline2` is empty

**Comment by tigexplorer** [comment]
Nothing changed after I removed `openjdk version "11.0.10" 2021-01-19` and installed `adoptopenjdk-11-hotspot-jre`

**Comment by bertfrees** [comment]
Hi. For some reason the `java` command is not found. What does the command `type java` give you?

The safest is to set the `JAVA_HOME` variable. This way you have total control of which version of java is being used. You can set the variable in the file /etc/default/daisy-pipeline2.

**Comment by tigexplorer** [comment]
> type java
```
type java
java ist gehasht (/usr/bin/java)
```

**Comment by tigexplorer** [comment]
I have in `/etc/default/daisy-pipeline2`

```
# Configuration file for /etc/init.d/daisy-pipeline2

JAVA_HOME=/usr/bin/java

# Execute pipeline in remote mode and with authentication
#export PIPELINE2_WS_LOCALFS=true
#export PIPELINE2_WS_AUTHENTICATION=false

# Java heap size
#export JAVA_MIN_MEM=256M
#export JAVA_MAX_MEM=1G
#export JAVA_PERM_MEM=16M
#export JAVA_MAX_PERM_MEM=256M
```
`sudo service daisy-pipeline2 restart`

```
● daisy-pipeline2.service - LSB: Start and stop the DAISY Pipeline 2 server
     Loaded: loaded (/etc/init.d/daisy-pipeline2; generated)
     Active: active (exited) since Tue 2021-02-16 12:29:22 CET; 2s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 20914 ExecStart=/etc/init.d/daisy-pipeline2 start (code=exited, status=0/SUCCESS)

Feb 16 12:29:21 evi-note systemd[1]: Starting LSB: Start and stop the DAISY Pipeline 2 server...
Feb 16 12:29:22 note daisy-pipeline2[20936]: pipeline2: JAVA_HOME not set; results may vary
Feb 16 12:29:22 note daisy-pipeline2[20936]: pipeline2: java command not found
Feb 16 12:29:22 note systemd[1]: Started LSB: Start and stop the DAISY Pipeline 2 server.

```

**Comment by bertfrees** [comment]
> ```
> java ist gehasht (/usr/bin/java)
> ```

Yes, this is what I feared. This is not the output that the script expects. Using the JAVA_HOME or JAVA environment variable is your only option.

> ```
> # Configuration file for /etc/init.d/daisy-pipeline2
> JAVA_HOME=/usr/bin/java
> ```

You forgot `export`.

**Comment by bertfrees** [comment]
By the way there is a new version of Pipeline available which I recommend installing: http://daisy.github.io/pipeline/Download.html

**Comment by tigexplorer** [comment]
After fixing `export JAVA_HOME=/usr/bin/java` in `/etc/init.d/daisy-pipeline2` and installing `pipeline2-1.14.2_debian.deb` 

only one error is gone
```
● daisy-pipeline2.service - LSB: Start and stop the DAISY Pipeline 2 server
     Loaded: loaded (/etc/init.d/daisy-pipeline2; generated)
     Active: active (exited) since Tue 2021-02-16 13:02:26 CET; 10s ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 0 (limit: 4517)
     Memory: 0B
     CGroup: /system.slice/daisy-pipeline2.service

Feb 16 13:02:25 note systemd[1]: Starting LSB: Start and stop the DAISY Pipeline 2 server...
Feb 16 13:02:26 note daisy-pipeline2[21948]: pipeline2: JAVA_HOME is not valid: /usr/bin/java
Feb 16 13:02:26 note systemd[1]: Started LSB: Start and stop the DAISY Pipeline 2 server.
```

`/usr/bin/java` gives me

```
Verwendung: java [Optionen] <mainclass> [args...]
           (zur Ausführung einer Klasse)
   oder  java [Optionen] -jar <jarfile> [args...]
           (zur Ausführung einer JAR-Datei)
   oder  java [Optionen] -m <module>[/<mainclass>] [args...]
       java [Optionen] --module <module>[/<mainclass>] [args...]
            (zur Ausführung der Hauptklasse in einem Modul)

 Argumente, die auf die Hauptklasse folgen, -jar <jarfile>, -m oder --module
 <module>/<mainclass> werden als Argumente für die Hauptklasse übergeben.

 wobei "Optionen" Folgendes umfasst:

    -cp <Klassensuchpfad mit Verzeichnissen und ZIP-/JAR-Dateien>
    -classpath <Klassensuchpfad mit Verzeichnissen und ZIP-/JAR-Dateien>
.....
```

**Comment by tigexplorer** [comment]
> export JAVA=/usr/bin/java

Ah, sorry, I've changed  `JAVA_HOME=/usr/bin/java` to `export JAVA=/usr/bin/java`

and now, the server is running
```
● daisy-pipeline2.service - LSB: Start and stop the DAISY Pipeline 2 server
     Loaded: loaded (/etc/init.d/daisy-pipeline2; generated)
     Active: active (running) since Tue 2021-02-16 14:13:18 CET; 2s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 22847 ExecStart=/etc/init.d/daisy-pipeline2 start (code=exited, status=0/SUCCESS)
      Tasks: 22 (limit: 4517)
     Memory: 233.3M
     CGroup: /system.slice/daisy-pipeline2.service
             └─22857 /usr/bin/java -server -Dcom.sun.management.jmxremote --illegal-access=warn --add-opens java.base/java.security>

Feb 16 14:13:13 note systemd[1]: Starting LSB: Start and stop the DAISY Pipeline 2 server...
Feb 16 14:13:18 note systemd[1]: Started LSB: Start and stop the DAISY Pipeline 2 server.
```
but I've no success with `dp2`

```
Der Befehl 'dp2' wurde nicht gefunden, meinten Sie:

  Befehl 'dpe' aus dem deb delly (0.8.2-1)
  Befehl 'dp' aus dem deb speech-tools (1:2.5.0-8build1)
  Befehl 'dpt' aus dem deb pkg-perl-tools (0.59)
  Befehl 'd52' aus dem deb d52 (3.4.1-1.1build1)

Versuche: sudo apt install <deb name>

```
nor with `java dp2 help`

```
Fehler: Hauptklasse dp2 konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: dp2

```
and this gives me an internal server error 
`/opt/daisy-pipeline2-cli/dp2 daisy202-validator --ncc /home/note/test_2021_01/ncc.html --output test`
```
Job f85ebb50-9aaf-494f-bf0d-c9364b648a5d sent to the server
______________________________________________________________________________
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0.0% Error:
	Server error: Internal Server Error
```

**Comment by bertfrees** [comment]
Can you attach the webservice log please? You can find it in /var/log/daisy-pipeline2.

**Comment by tigexplorer** [comment]
> /var/log/daisy-pipeline2

https://gist.github.com/tigexplorer/0a82126db3d1d98a665e4f60c6eacbc1

**Comment by tigexplorer** [comment]
> By the way there is a new version of Pipeline available which I recommend installing: http://daisy.github.io/pipeline/Download.html

On http://daisy.github.io/pipeline/Download.html the Latest major version: 1.14.2, like suggested, is described to include the cli. 

So I purged the previously installed `cli-2.1.4-linux_386.deb`.
Now I get this
```
/opt/daisy-pipeline2-cli/dp2 daisy202-validator --ncc /home/note/test_2021_01/ncc.html --output test
bash: /opt/daisy-pipeline2-cli/dp2: Datei oder Verzeichnis nicht gefunden
```
(/opt/daisy-pipeline2-cli/dp2: not found)
Maybe, the cli is NOT in 1.14.2?

**Comment by bertfrees** [comment]
Yeah the description on that page is wrong. You still need cli-2.1.4-linux_386.deb.

**Comment by tigexplorer** [comment]
Ah, perhaps, deinstalling and reinstalling of `cli-2.1.4-linux_386.deb` does the trick. 
Now it works.
Thanx for your advices!

**Comment by bertfrees** [comment]
Good to hear it works now. I think the internal server error you got is something that could possibly happen again though. Please let me know if it happens again with the latest version (1.14.2).
