### ISSUE TITLE
failure to build on Linux

### ISSUE THREAD

**Issue by VK2BEA** [daisy/pipeline#588]
currently get error

/bin/bash: -c: line 4: unexpected EOF while looking for matching `''
/bin/bash: -c: line 5: syntax error: unexpected end of file
make: *** [.make/main.mk:275: .group-eval] Error 1

<details><summary>Full log</summary><pre><code>
make dist-zip-linux
make[1]: Entering directory '/home/michael/Downloads/pipeline/website'
bundle install --path gems
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'gems'`, and stop using this flag
Fetching gem metadata from https://rubygems.org/.........
Fetching public_suffix 4.0.6
Installing public_suffix 4.0.6
Fetching addressable 2.7.0
Installing addressable 2.7.0
Fetching builder 3.2.4
Installing builder 3.2.4
Using bundler 2.1.4
Fetching coderay 1.1.0
Installing coderay 1.1.0
Fetching colorator 1.1.0
Installing colorator 1.1.0
Fetching mini_portile2 2.3.0
Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.4
Installing nokogiri 1.8.4 with native extensions
ls
Fetching commaparty 0.0.2
Installing commaparty 0.0.2
Fetching link_header 0.0.8
Installing link_header 0.0.8
Fetching rdf 1.1.15
Installing rdf 1.1.15
Fetching sxp 0.1.5
Installing sxp 0.1.5
Fetching ebnf 0.3.9
Installing ebnf 0.3.9
Fetching ffi 1.14.2
Installing ffi 1.14.2 with native extensions
Fetching forwardable-extended 2.6.0
Installing forwardable-extended 2.6.0
Fetching github-markup 1.4.0
Installing github-markup 1.4.0
Fetching tilt 2.0.10
Installing tilt 2.0.10
Fetching haml 4.0.7
Installing haml 4.0.7
Fetching htmlentities 4.3.4
Installing htmlentities 4.3.4
Fetching rb-fsevent 0.10.4
Installing rb-fsevent 0.10.4
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching sass-listen 4.0.0
Installing sass-listen 4.0.0
Fetching sass 3.7.4
Installing sass 3.7.4
Fetching jekyll-sass-converter 1.5.2
Installing jekyll-sass-converter 1.5.2
Fetching listen 3.3.3
Installing listen 3.3.3
Fetching jekyll-watch 1.5.1
Installing jekyll-watch 1.5.1
Fetching kramdown 1.17.0
Installing kramdown 1.17.0
Fetching liquid 3.0.6
Installing liquid 3.0.6
Fetching mercenary 0.3.6
Installing mercenary 0.3.6
Fetching pathutil 0.16.2
Installing pathutil 0.16.2
Fetching rouge 1.11.1
Installing rouge 1.11.1
Fetching safe_yaml 1.0.5
Installing safe_yaml 1.0.5
Fetching jekyll 3.3.0
Installing jekyll 3.3.0
Fetching mustache 1.0.2
Installing mustache 1.0.2
Fetching net-http-persistent 2.9.4
Installing net-http-persistent 2.9.4
Fetching rdf-aggregate-repo 1.1.0
Installing rdf-aggregate-repo 1.1.0
Fetching rdf-xsd 1.1.4
Installing rdf-xsd 1.1.4
Fetching rdf-rdfa 1.1.6
Installing rdf-rdfa 1.1.6
Fetching rdf-turtle 1.1.7
Installing rdf-turtle 1.1.7
Fetching sparql-client 1.1.6
Installing sparql-client 1.1.6
Fetching sparql 1.1.8
Installing sparql 1.1.8
Bundle complete! 13 Gemfile dependencies, 41 gems now installed.
Bundled gems are installed into `./gems`
Post-install message from haml:

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841

Post-install message from rdf-xsd:

    For best results, use nokogiri and equivalent-xml gems as well.
    These are not hard requirements to preserve pure-ruby dependencies.
  mkdir -p target/maven/
if ! RUBYOPT=-W0 bundle exec make/make_pom.rb src/_data/versions.yml src/_data/modules.yml src/_data/api.yml > target/maven/pom.xml; then \
	rm -f target/maven/pom.xml && \
	exit 1; \
fi
make[1]: Leaving directory '/home/michael/Downloads/pipeline/website'
/bin/bash: -c: line 4: unexpected EOF while looking for matching `''
/bin/bash: -c: line 5: syntax error: unexpected end of file
make: *** [.make/main.mk:275: .group-eval] Error 1
</code></pre></details>

**Comment by bertfrees** [comment]
Can you send me the contents of .make/target/commands?

**Comment by VK2BEA** [comment]
I don't see this file in .make/target

**Comment by VK2BEA** [comment]
No change ...
[industrynumbers Downloads] $ cd pipeline/
[industrynumbers pipeline] $ make dist-zip-linux
/bin/bash: -c: line 4: unexpected EOF while looking for matching `''
/bin/bash: -c: line 5: syntax error: unexpected end of file
make: *** [.make/main.mk:275: .group-eval] Error 1
[industrynumbers pipeline] $ ls .make/target/
effective-pom.xml  effective-settings.xml  gradle-pom.xml  maven-aggregators  maven.mk  maven-modules  mk  poms  properties
[industrynumbers pipeline] $ make -v
GNU Make 4.3
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[industrynumbers pipeline] $

**Comment by bertfrees** [comment]
OK sorry, I thought that might have been the problem but it seems to be something else. Hard to tell what though. Is there a .make/target/env (also when you delete it first)?

By the way, you can bypass the whole "group-eval" thing by doing

    make SKIP_GROUP_EVAL_TARGET=true EVAL=eval dist-zip-linux

Not ideal because I'd like to track down the bug, but this could get you going for now.

**Comment by VK2BEA** [comment]
Yes, that builds OK.
Sorry about the confusion with the other issue!

**Comment by bertfrees** [comment]
I think I messed something up in my fancy code to print the environment variables set by the Makefile :-(. Working on a fix.
