### ISSUE TITLE
DTBook to Daisy3

### ISSUE THREAD

**Issue by mmartida** [daisy/pipeline#589]
Hi again,

this is a request instead of a standard issue.

Is possible to get the Daisy 3 format from DTBook directly on Pipeline 2?
If not, is possible to add some kind of script or option to pipeline code to achieve that goal?

Is possible that in oncomming new versions the Pipeline 2 would includes that feature?
If this last option to be possible, more or less when would be released that new version of Pipeline 2?

What i mean is to pass directly from DTBook to Daisy 3 on one single step instead of two steps DTBook -> Daisy 2.02 and then Daisy 2.02 -> Daisy 3.

Thanks

**Comment by bertfrees** [comment]
Hi. We already have a "DTBook to DAISY 3" script. No need to go through DAISY 2.0.2. See http://daisy.github.io/pipeline/Get-Help/User-Guide/Scripts/dtbook-to-daisy3/.

**Comment by mmartida** [comment]
And going to contrary way?
from  DTBook to Daisy 2.02?

Is someway possible to get any way to transform from DTBook to Daisy 2.02 like on Pipeline 1?

Thanks

**Comment by bertfrees** [comment]
To produce a DAISY 2.02 from a DTBook you can first produce a DAISY 3, and then downgrade it to DAISY 2.02.
