### ISSUE TITLE
epub3-to-epub3 strips doctype from XHTML documents in input EPUB 3 fileset

### ISSUE THREAD

**Issue by martinpub** [daisy/pipeline#613]
### Expected Behavior
epub3-to-epub3 preserves doctype from XHTML documents in input EPUB 3 fileset.

### Actual Behavior
epub3-to-epub3 strips doctype from XHTML documents in input EPUB 3 fileset.

### Steps to Reproduce
1. With an input EPUB 3 containing content file or nav.xhtml with `<!DOCTYPE html>`
2. Run `dp2 epub3-to-epub3 --source source.epub --data source.zip --output outputdir/ --tts false --braille false --sentence-detection false --update-lang-attributes true --update-identifier-in-content-docs true --update-title-in-content-docs true --metadata sample_metadata.xml`

### Details
As XHTML 5.0 is already explicitly specified in [EPUB 3](https://www.w3.org/publishing/epub3/epub-contentdocs.html#sec-xhtml), I'm not sure if the HTML 5 doctype is strictly needed. However, I was uncertain if this can cause errors in certain reading systems/processing tools that might rely on HTML 5 parsing?

### Environment
* Operating system: Ubuntu GNU/Linux
* DAISY Pipeline 2 version: 1.14.4-SNAPSHOT (off of [this specific MTM fork tag](https://github.com/mtmse/pipeline/tree/20210630))
* Interface: Command Line

### Logs
[Logs](https://gist.github.com/martinpub/cd908695e63bc966c0895cda64016605)

**Comment by bertfrees** [comment]
Thanks for the report. It seems XProc does not automatically add the doctype when storing documents and it is currently not possible to set the "html-version" serialization parameter.

**Comment by martinpub** [comment]
Thanks for the fix @bertfrees!
