### ISSUE TITLE
Embedded fonts not preserved after epub2-to-epub3 conversion

### ISSUE THREAD

**Issue by bitsgalore** [daisy/pipeline#618]
### Expected Behavior

Embedded (TrueType) fonts in EPUB 2 files are preserved after converting to EPUB 3.

### Actual Behavior

Fonts are lost after conversion.

### Steps to Reproduce

Source EPUB is [available here](https://www.bibliotheek.nl/bnldam/bestanden/beet005came07_01.epub). I converted this file to EPUB 3 using the following command:

```
/opt/daisy-pipeline2-cli/dp2 epub2-to-epub3 --source beet005came07_01.epub --output ./test --validation report
```

Console output reports conversion is successful (I don't think the Java warning is related to my issue, but I'm including it here just jn case):

```
[INFO]     Loading EPUB 2
[WARNING]    Failed to load content types: /usr/lib/jvm/java-11-openjdk-amd64/lib/content-types.properties
[INFO]       Running EPUBCheck
[INFO]     Converting to EPUB 3
[INFO]     Storing EPUB 3
______________________________________________________________________________
The job has been deleted from the server
Job finished with status: SUCCESS
```

The source EPUB contains a "fonts" folder with 5 TrueType font files. This folder (and the fonts) are missing in the output file (which for this ebook results in some pretty major formatting changes).

### Environment

* Operating system: Linux Mint 20.1 Ulyssa
* DAISY Pipeline 2 version:  1.14.4
* DAISY Pipeline 2 CLI version: v2.1.5 
* Interface: Command Line

**Comment by bertfrees** [comment]
Thanks for the good description of the problem. We'll look into it!

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/29d4848d0c4e2d0a06963617ff945cf7fc1e5ac3
