### ISSUE TITLE
Pipeline hangs when using Google TTS adapter

### ISSUE THREAD

**Issue by avjves** [daisy/pipeline#619]
### Expected Behavior
I want to run an epub through the pipeline and create a DAISY file from it with Google TTS enabled.

### Actual Behavior
Everything goes smoothly at beginning. The logs signal that the progress is increasing - so it's calling the API correctly.
However, after a while it just stops and hangs there. No errors, no nothing. It just sits there without doing anything.
Depending on the script used, I can see some generated files in the temporary directory as well. 

### Steps to Reproduce
0. Use Pipeline 2 1.14.4
1. Use the EPUB sample from Daisy samples ( [Valentin Haüy](https://dl.daisy.org/samples/epub/valentin-hauy.epub) ).
2. Use the script "EPUB TO DAISY"
3. Use TTS config: 
````
    <config>
      <property key="log" value="true"/>
      <property key="org.daisy.pipeline.tts.google.apikey" value="APIKEY"/>
      <voice engine="google" name="en-US-Wavenet-D" gender="female-adult" priority="100" lang="en"/>
    </config>
````
4. Run

### Details
I actually wanted to make a custom TTS-adapter for my own TTS-service, but it had the same issues (the custom adapter was just a modified google TTS adapter). Both adapters function the same, but I can actually see the requests hitting my server with the custom adapter, and I can see that it just stops sending requests. No 500s or anything like that. But for this issue I'll focus on the official Google TTS adapter, as I could've broken something when building this myself :)

Using just the ESpeak adapter everything seems to work just fine.

I've tried this on Windows 10, Linux Manjaro and Debian. 
I've also tried different scripts: DTBook to DAISY/EPUB etc. I get the same "hanging" issue there and sometimes I also see a "something went wrong.. (check TTS logs for more)". But no TTS logs are generated before its ready and as it hangs - no TTS logs.

The only log I can find is the job's log. Is there a more in-depth log somewhere?

### Environment
* Operating system:  Windows 10 64-bit
* DAISY Pipeline 2 version: 1.14.4
* Interface:  GUI, WebUI

### Logs
[Logs](https://gist.github.com/avjves/032d2829c04e9a173113979b9de00c42)

**Comment by bertfrees** [comment]
Hi, thanks for the report. No, I don't think you can get any more in-depth logs. The "TTS log" would indicate which sentences are being processed when the script starts hanging, and you would get stack traces for synthesis errors, but the log file is indeed only written at the end.

Before we investigate this further? Could you please check whether setting the "org.daisy.pipeline.tts.threads.number" property to "1" solves anything?

**Comment by avjves** [comment]
I tried running it again with "org.daisy.pipeline.tts.threads.number" set to 1 and now there's no progress report in the log, so it seems that it hangs very early. The last line in the logs is 
2021-12-14 19:50:44,349 [INFO ] o.d.p.t.s.c.impl.SynthesizeStep - Encoding threads started.


I observed similar behavior with the custom adapter, where the higher I set the "org.daisy.pipeline.tts.threads.speaking.number" value the further I can get. With speaking threads set to 1, it hangs after just a few requests. I have't compiled any stats on this though, so it may be that it's just each thread gets stuck after X amount of requests or something and with more threads it naturally gets further then.

**Comment by bertfrees** [comment]
Hi @avjves. I have looked into this issue. In your custom TTS adapter, don't return such a high number for `expectedMillisecPerWord()`. This is what is causing the Google TTS adapter to hang. You can just remove the method, the default value will be fine.

**Comment by avjves** [comment]
Hey,
I tested this and yup, works!
Thanks a ton!

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/57685690f34498b516f95c900439cf6216adb2cb
