### ISSUE TITLE
Converted EPUB3 from DTBook has Arabic in page listing navigation heading

### ISSUE THREAD

**Issue by jbrugge** [daisy/pipeline#674]
### Expected Behavior
When running the dtbook-to-epub3 script on English-language books, the EPUB3 result should have a toc.xhtml with a page listing that has a heading of "Page lists" or similar.

### Actual Behavior
When we convert some English-language DAISY books to EPUB3, the toc.xhtml has Arabic text for the page list heading, and English text for everything else. That is to say, the page list navigation section starts like this:
    `<nav epub:type="page-list" hidden="">
        <h1>قائمة الصفحات</h1>`

### Steps to Reproduce
1. This is running the Pipeline2 as a web service in a Docker container. I'm using a docker-compose setup like the following to reproduce the error we see in our server environment.
    pipeline:
        image: daisyorg/pipeline:v1.14.7
        environment:
            - TZ=America/Los_Angeles
            - JAVA_OPTS=-server -Xms2560M -Xmx2560m -XX:MetaspaceSize=64m -XX:MaxMetaspaceSize=756m
            - PIPELINE2_WS_HOST=0.0.0.0
            - PIPELINE2_WS_AUTHENTICATION=false
            - PIPELINE2_WS_LOCALFS=false
        ports:
            - 8181:8181
        volumes:
            - $HOME/logs/daisy-pipeline:/opt/daisy-pipeline2/data/job
        entrypoint: /opt/daisy-pipeline2/bin/pipeline2
        container_name: dev-pipeline-assembly

2. I create a job request file (should be attached) and call the script using curl.
     $ curl --form job-data='@The_Adventures_of_Sherlock_Holmes.zip' --form job-request='@pipelineRequest_Sherlock.xml' http://localhost:8181/ws/jobs
3. Using the jobId that comes back in the XML response, I ask for the job results ZIP file.
    $ curl http://localhost:8181/ws/jobs/a7668b5f-71f8-457e-b157-be1bc4f3efd4/result -o Sherlock_epub3.zip
4. When I open up the ZIP file and then extract the EPUB package, the toc.xhtml has the Arabic text under the nav page list heading.

### Details

Input file: [The_Adventures_of_Sherlock_Holmes.zip](https://github.com/daisy/pipeline/files/11290990/The_Adventures_of_Sherlock_Holmes.zip)
Job request file:
    `<jobRequest xmlns='http://www.daisy.org/ns/pipeline/data'>
    <script href='http://localhost:8181/ws/scripts/dtbook-to-epub3'/>
    <input name='source'>
        <item value='The_Adventures_of_Sherlock_H.xml'/>
    </input>
    <option name='assert-valid'>false</option>
    </jobRequest>`

### Environment
* Operating system: Linux 64-bit
* DAISY Pipeline 2 version: 1.14.7
* Interface: web service API

### Logs

[Logs]( https://gist.github.com/jbrugge/c8932923216f25aa15f3d02c597e9748 )

**Comment by bertfrees** [comment]
Thanks for the detailed report. I can reproduce the issue.

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/2a40c5fd7b0a015e70f34c13e228b5659d6a7acd
