### ISSUE TITLE
DTBook to HTML should preserving heading structure

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/pipeline#678]
### Actual Behavior
All headings in the HTML are h1.

### Steps to Reproduce

1. Find a valid DTBook file with multiple heading levels.
2. Convert using DTBook to HTML scripts.
3. Observe that the HTML only has 1.

### Details
If necessary, describe your problem in more detail.

None.

### Environment
* Operating system: Windows 11 64-bit }
* DAISY Pipeline API 1.0

**Comment by bertfrees** [comment]
Agree.
