### ISSUE TITLE
DTBook to EPUB should preserve heading hierarchy 

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/pipeline#680]
### Expected Behavior
I am trying to convert NIMAS files to EPUB. For this, I am selecting the DTBook to EPUB script. When the script finishes, all headings in the EPUB are at a h1. The DTBook files has multiple levels of headings.

### Actual Behavior

The EPUB only had level 1 in the chapters.

### Steps to Reproduce

1. Select a DTBook file that has multiple levels of headings.
2. Use the DAISY Pipeline App  and select the DTBook to EPUB script.
3. Review the resulting EPUB and notice that all headings have been mapped to an h1.

### Details
I will be working with the NIMAC to get the Pipeline team access to about 10 files.

### Environment
* Operating system: Windows 11 64-bit 
* DAISY Pipeline App 1.0

### Logs
Visit [Providing Logs in an Issue](https://daisy.github.io/pipeline/Get-Help/Issue-Tracker.html) for details on how to provide your log files.

[Logs]( link goes here )

**Comment by bertfrees** [comment]
Thanks. Will be fixed when https://github.com/daisy/pipeline/issues/678 is fixed.

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/21294fbd4be0e774c87e8e479b9170299858b46c
