### ISSUE TITLE
EPUB Enhancer script is missing documentation

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/pipeline#681]
### Expected Behavior
I wanted to read the script documentation for EPUB Enhancer, but nothing was present.

### Actual Behavior
I selected the EPUB Enhancer script, and when I tabbed to where the "read script documentation" normally is, there was no link to the documentation.

### Steps to Reproduce

1. Start a new job
2. Select EPUB enhancer
3. tab to read the script documentation, but none is present.
4. 

### Details
If necessary, describe your problem in more detail.

None.

### Environment
* Operating system: __example__: Windows 10 64-bit }
* DAISY Pipeline 2 version: _example_: 1.10.3
* Interface: _example_: GUI, Command Line, or WebUI

### Logs
Visit [Providing Logs in an Issue](https://daisy.github.io/pipeline/Get-Help/Issue-Tracker.html) for details on how to provide your log files.

[Logs]( link goes here )

**Comment by bertfrees** [comment]
Thanks for the catch. Will be fixed in next release.
