### ISSUE TITLE
DTBook scripts ignore "enum" and "start" attributes on ordered list

### ISSUE THREAD

**Issue by nicolegaines** [daisy/pipeline#685]
### Expected Behavior

Per the DAISY Structure Guidelines, there is support in DAISY for non-integer lists. Using the enum attribute, an ordered list <list type="ol"> can have a numbering value that is an integer, upper case letter, lower case number, or Roman numeral. Similarly, the start    attribute can be used to begin numbering at a number other than "1" (or "a", "A," or "i"). 

I marked up a NIMAS XML file with four different types of lists to test the RTF and HTML conversions. The test lists are found on page 2 in the XML and RTF files (attached). 

In running NIMAS XML file through the Pipeline 2 (2023), I found that the tool does not appear to recognize the enum or start attributes. All lists are rendered with integer numbering, beginning with 1, regardless of the values entered for enum and start. 

Since it is not unusual for lists to appear in K-12 instructional materials with numbering that uses letters, a bug fix to address the enum issue would be helpful for users working with NIMAS files. There are probably fewer cases where the "start" attribute comes into play, but it would be helpful for the Pipeline to support that attribute, as well. 

Just let me know if you need any further information! Thanks!

1.
[9780547029146NIMAS_2.zip](https://github.com/daisy/pipeline/files/11655081/9780547029146NIMAS_2.zip)

### Details
If necessary, describe your problem in more detail.

Windows 10 64-bit
App version: 1.0.0-RC2
Engine version: 1.14.11
Engine is running on 127.0.0.1:49152/ws
None.

**Comment by bertfrees** [comment]
The `enum` attribute is now taken into account in the HTML conversion. The `start` was already taken into account.

**Comment by bertfrees** [comment]
I also have a fix for the RTF conversion, but unfortunately can not test it at the moment because I don't have MS Word installed (and TextEdit and LibreOffice on macOS give unsatisfying results).

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/70c03a14766ea60474c743eca040300be10e7ce8.
