### ISSUE TITLE
DTBook to RTF : wrong type of field displayed in UI

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline#692]
### Expected Behavior
When opening the DTBook to RTF script in the daisy pipeline app, the "Include table of content" and "Include page number" should be displayed as checkboxes

### Actual Behavior
The script form the daisy pipeline app currently display text fields with textual value "false" in it.

### Steps to Reproduce
Open the daisy pipeline app and select the Dtbook to rtf script.

### Details
After checking the script code, the two options are not associated to a `px:type="boolean"` attribute.

### Environment
* Operating system: : Windows 10 64-bit
* DAISY Pipeline 2 version: : 1.14.14
* Interface: : Daisy Pipeline App 1.1.0

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline/pull/693.
