### ISSUE TITLE
EPUB 3 script for 9780895442635NIMAS generates error

### ISSUE THREAD

**Issue by nicolegaines** [daisy/pipeline#694]
NIMAS file from a new publisher fails in the DTBook to EPUB 3 conversion generating this error:

ERROR - No id generated for : element not included in "for-elements" parameter. (Please see detailed log for more info.)

Windows 10 Pro
Version 22H2

App version: 1.1.0
Engine version: 1.14.14
Engine is running on 127.0.0.1:49152/ws 

[error_log_pipeline_9780895442635NIMAS.txt](https://github.com/daisy/pipeline/files/12279901/error_log_pipeline_9780895442635NIMAS.txt)

**Comment by bertfrees** [comment]
Thanks for the report! This bug will be fixed in the next release (October).
