### ISSUE TITLE
ACE notes "serious" issue for incorrect lang attribute of html files in generated EPUB3

### ISSUE THREAD

**Issue by jbrugge** [daisy/pipeline#699]
### Expected Behavior
When running the dtbook-to-epub3 script on DAISY books, the EPUB3 result should have HTML files with a correct "lang" attribute for the <html> element.

### Actual Behavior
Running ACE against the EPUB3 output generates a report pointing out the missing property.
`{
          "@type": "earl:assertion",
          "earl:result": {
            "earl:outcome": "fail",
            "dct:description": "Value of lang attribute not included in the list of valid languages",
            "earl:pointer": {
              "cfi": [
                "/"
              ],
              "css": [
                "html"
              ]
            },
            "html": "<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"eng\">"
          },
          "earl:assertedBy": "aXe",
          "earl:mode": "automatic",
          "earl:test": {
            "earl:impact": "serious",
            "dct:title": "html-lang-valid",
            "dct:description": "Ensures the lang attribute of the <html> element has a valid value",
            "help": {
              "url": "http://kb.daisy.org/publishing/docs/html/lang.html",
              "dct:title": "Language",
              "dct:description": "<html> element must have a valid value for the lang attribute"
            },
            "rulesetTags": [
              "cat.language",
              "wcag2a",
              "wcag311",
              "ACT",
              "TTv5",
              "TT11.a"
            ]
          }
        }
`

### Steps to Reproduce
I'm running the Pipeline2 as a web service in a Docker container, as described in #674.

The script is run via curl:
`$ curl -v -X POST --form job-data='@Charlotte_s_Web.zip' --form job-request='@pipelineRequest_Charlotte.xml' http://localhost:8181/ws/jobs`

The job request file looks like this:
`<jobRequest xmlns='http://www.daisy.org/ns/pipeline/data'>
    <script href='http://localhost:8181/ws/scripts/dtbook-to-epub3'/>
    <input name='source'>
    <item value='Charlotte_s_Web.xml'/>
    </input>
    <option name='assert-valid'>false</option>
</jobRequest>
`

The ACE report was then generated with this:
`$ ace --subdir --silent --outdir ace_charlotte Charlotte_s_Web.epub`

### Details
The input DAISY package can be provided by an alternate channel.

The [guidance from the W3C](https://www.w3.org/International/questions/qa-html-language-declarations#attributes) suggests that we might want both "lang=" and "xml:lang=" as attributes.

### Environment
* Operating system: Linux 64-bit
* DAISY Pipeline 2 version: 1.14.14
* Interface: web service API
* ACE: 1.3.1

### Logs
[ACE JSON report](https://gist.github.com/jbrugge/d7844a68a2be77327d72f960e2b2131b)

**Comment by bertfrees** [comment]
@jbrugge Would it be possible to email me the "Charlotte_s_Web.xml" please?

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/efb1b61b38395b33a5d0a942d27a761d8ffd95c4
