### ISSUE TITLE
ACE notes "serious" error for missing lang attribute in OPF of generated EPUB3

### ISSUE THREAD

**Issue by jbrugge** [daisy/pipeline#700]
### Expected Behavior
When running the dtbook-to-epub3 script on DAISY books, the EPUB3 result should have an OPF file with a lang attribute describing the language of the OPF XML.

### Actual Behavior
Running ACE against the EPUB3 output generates a report pointing out the missing property.
`        {
          "@type": "earl:assertion",
          "earl:result": {
            "earl:outcome": "fail",
            "dct:description": "The language must be specified (xml:lang in OPF package)"
          },
          "earl:assertedBy": "Ace",
          "earl:mode": "automatic",
          "earl:test": {
            "earl:impact": "serious",
            "dct:title": "epub-lang",
            "dct:description": "Ensures the OPF XML language is provided",
            "help": {
              "url": "http://kb.daisy.org/publishing/docs/epub/language.html",
              "dct:title": "Language",
              "dct:description": "Add the missing OPF xml:lang attribute"
            },
            "rulesetTags": [
              "EPUB"
            ]
          }
        },
`

### Steps to Reproduce
The sample book in #674 exhibits this issue, so refer to the EPUB3 output from that.

The ACE report was then generated with this:
`$ ace --subdir --silent --outdir ace_sherlock The_Adventures_of_Sherlock_H.epub`

### Environment
* Operating system: Linux 64-bit
* DAISY Pipeline 2 version: 1.14.7
* Interface: web service API
* ACE: 1.3.1

### Logs

[ACE JSON report]( https://gist.github.com/jbrugge/bc5bef0952f6c1b03a5b2f97ef7a7473 )

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/efb1b61b38395b33a5d0a942d27a761d8ffd95c4
