### ISSUE TITLE
epubcheck notes "ERROR" for rule OPF-028 in generated EPUB3 OPF

### ISSUE THREAD

**Issue by jbrugge** [daisy/pipeline#701]
### Expected Behavior
When running the dtbook-to-epub3 script on DAISY books that have pagebreaks in them, the EPUB3 result should have an OPF file that passes epubcheck.

### Actual Behavior
Running epubcheck against the generated output generates a report noting an issue with a meta item in the OPF.
`{
    "ID" : "OPF-028",
    "severity" : "ERROR",
    "message" : "Undeclared prefix: \"dc\".",
    "additionalLocations" : 0,
    "locations" : [ {
      "url" : {
        "opaque" : false,
        "hierarchical" : true
      },
      "path" : "EPUB/package.opf",
      "line" : 2,
      "column" : 1359,
      "context" : null
    }
`

The line that this points to in the attached EPUB3 OPF is this:
`<meta xmlns:f="http://www.daisy.org/ns/pipeline/internal-functions" xmlns:pf="http://www.daisy.org/ns/pipeline/functions" xmlns:rdfa="rdfa-functions" property="dc:date">2023-04-20T22:13:09+00:00</meta>`

### Steps to Reproduce
The sample book in #674 exhibits this issue, so refer to the EPUB3 output from that.

The epubcheck report was then generated with this:
`epubcheck --json Sherlock_Holmes-epubcheck.json The_Adventures_of_Sherlock_H.epub`

### Environment
* Operating system: Linux 64-bit
* DAISY Pipeline 2 version: 1.14.7
* Interface: web service API
* epubcheck : 5.0.1

### Logs
[epubcheck JSON report]( https://gist.github.com/jbrugge/f5abd07ca7580e3eedee698ec8eaff94 )

**Comment by bertfrees** [comment]
Fixed by https://github.com/daisy/pipeline-modules/commit/efb1b61b38395b33a5d0a942d27a761d8ffd95c4
