### ISSUE TITLE
NIMAS to EPUB 3 script fails when images do not have an id attribute?

### ISSUE THREAD

**Issue by nicolegaines** [daisy/pipeline#725]
In trying to convert a NIMAS file to EPUB, the pipeline generated this error:

ERROR - An empty sequence is not allowed as the value of variable $img-id (Please see detailed log for more info.)

I have attached the complete error log below. 

This same file passes the Pipeline's NIMAS validation script with no errors. As far as I can find in the DAISY Structure Guidelines, the id attribute is not required on the <img> tags. If this error is not related to the id attribute on <img> please let me know and I can do some further investigating. Thanks. 

App version: 1.1.0
Engine version: 1.14.14
Engine is running on 127.0.0.1:49152/ws
Windows 10 Professional
Version 22H2

[9781640533554NIMAS_pipeline_error_log.txt](https://github.com/daisy/pipeline/files/12874145/9781640533554NIMAS_pipeline_error_log.txt)

**Comment by bertfrees** [comment]
Hi Nicole. Could this be due to an `imggroup` with a `caption` but without an `img`? That is indeed valid DTBook but the converter doesn't seem to handle it.

**Comment by nicolegaines** [comment]
Hi, Bert. Thanks for taking a look. I just discovered in taking a closer look at the XML that the NIMAS conversion vendor did some really odd tagging with the <imggroup>. There is an image, but the vendor nested the <caption> under the <prodnote> and inside a second <imggroup> tag. We're going to require that they correct this tagging and then I will give it another try. I'll keep you posted. Thanks!

________________________________

**Comment by bertfrees** [comment]
OK.

FYI the bug has been fixed and this fix will be included in the next release.
