### ISSUE TITLE
DTBook to DAISY3 - issue with mathml to ssml conversion

### ISSUE THREAD

**Issue by NPavie** [daisy/pipeline#780]
While testing a conversion with a test document, I stumbled on an error when trying to convert a dtbook with mathml into an audio-only daisy3.

### Expected Behavior

Successfully convert a dtbook containing mathml elements to a daisy3 audio only file

### Actual Behavior

The pipeline job stops with the following messages :
```
SSML generation for DTBook
ERROR - An empty sequence is not allowed as the third argument of fn:key() (Please see detailed log for more info.)
```

### Steps to Reproduce

1. use the dtbook provided in [dtbook_sample_with_math.zip](https://github.com/user-attachments/files/15551728/dtbook_sample_with_math.zip)
2. In the daisy pipeline app 1.4, launch a dtbook to daisy3 (TTS enhanced) conversion of the dtbook xml with the following settings
- Enable text-to-speech: true
- With text: false
- Detect words: false

### Environment
* Operating system: Windows 11 64-bit 
* DAISY Pipeline 2 version: 1.14.19-SNAPSHOT
* Interface: : Daisy pipeline app 1.4

### Logs

[job.log](https://github.com/user-attachments/files/15551767/job.log)

**Comment by bertfrees** [comment]
Thanks. I hope I didn't mess up during a refactoring.
